name:                bomberman-player
version:             0.1.0.0
git:                 "https://gitlab.com/d12frosted/bomberman-player"
license:             BSD3
author:              "Boris Buliga"
maintainer:          "boris@d12frosted.io"
copyright:           "2019 Boris Buliga"

extra-source-files:
- README.org
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Development

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/d12frosted/bomberman-player#readme>

dependencies:
- attoparsec
- base >= 4.7 && < 5
- bytestring
- comonad
- hashable
- random
- rio
- text
- time

library:
  source-dirs: src

ghc-options:
  - -Wall

executables:
  bomberman-bot:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    dependencies:
    - bomberman-player
    - mtl
    - network
    - optparse-applicative
    - websockets

tests:
  bomberman-player-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bomberman-player
    - tasty
    - tasty-hunit
    - tasty-quickcheck
